version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: footlink_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: footlink
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - footlink_data:/var/lib/postgresql/data
      - ./ssl:/var/lib/postgresql/ssl:ro
      - ./postgres_config/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    secrets:
      - db_user
      - db_password
    command: >
      postgres -c ssl=on
               -c ssl_cert_file='/var/lib/postgresql/ssl/server.crt'
               -c ssl_key_file='/var/lib/postgresql/ssl/server.key'
               -c ssl_ca_file='/var/lib/postgresql/ssl/ca.crt'

volumes:
  footlink_data:

secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
